site_name: TI307 & TI307P - Introduction au système Linux

repo_url: https://github.com/YvanGuifo/introduction-linux-fr

edit_uri: ""

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  favicon: assets/img/favicon.png
  logo: assets/img/logo.png
  font:
    text: Noto Sans
    code: Fira Mono
  # adding icons for blockquote
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/pin-16
      success: octicons/check-16
      question: fontawesome/solid/bullhorn
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  # enable switching from light to dark mode
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  # enable navigation tabs
  features:
    # - navigation.tabs
    - navigation.top
    - header.autohide
    - toc.integrate

markdown_extensions:
  # code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  # use icon and emoji
  # - attr_list
  # - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # create beautiful blockquote (said for sponsor only lul)
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  # formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # card grids
  - md_in_html
  # add mathjax.js
  - pymdownx.arithmatex:
      generic: true
  # use mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  # enable site search
  - search
  # enable tags in posts
  - tags
  # enable hidden pages for the corrige
  - awesome-pages


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YvanGuifo/introduction-linux-fr
      name: Github repo of this course

copyright:  TI307 & TI307P - Introduction au système Linux - Efrei Paris | Yvan GUIFO 2025 suite et continuité du travail de Rado Rakotonarivo 2024.
